"""Application-wide constants, enums, and system thresholds."""

# User Roles
ROLE_STUDENT = "STUDENT"
ROLE_RECRUITER = "RECRUITER"
ROLE_ADMIN = "ADMIN"
ALL_ROLES = [ROLE_STUDENT, ROLE_RECRUITER, ROLE_ADMIN]

# Drive Statuses
DRIVE_STATUS_DRAFT = "DRAFT"
DRIVE_STATUS_PUBLISHED = "PUBLISHED"
DRIVE_STATUS_CLOSED = "CLOSED"
DRIVE_STATUS_COMPLETED = "COMPLETED"
ALL_DRIVE_STATUSES = [
    DRIVE_STATUS_DRAFT,
    DRIVE_STATUS_PUBLISHED,
    DRIVE_STATUS_CLOSED,
    DRIVE_STATUS_COMPLETED,
]

# Application Statuses
APP_STATUS_PENDING = "PENDING"
APP_STATUS_UNDER_REVIEW = "UNDER_REVIEW"
APP_STATUS_SHORTLISTED = "SHORTLISTED"
APP_STATUS_ASSESSMENT = "ASSESSMENT"
APP_STATUS_INTERVIEW = "INTERVIEW"
APP_STATUS_SELECTED = "SELECTED"
APP_STATUS_REJECTED = "REJECTED"
ALL_APP_STATUSES = [
    APP_STATUS_PENDING,
    APP_STATUS_UNDER_REVIEW,
    APP_STATUS_SHORTLISTED,
    APP_STATUS_ASSESSMENT,
    APP_STATUS_INTERVIEW,
    APP_STATUS_SELECTED,
    APP_STATUS_REJECTED,
]

# Policy Status Constants
POLICY_PASS = "PASS"
POLICY_FAIL = "FAIL"